spring.application.name=Webpay Plus API
server.port=8080

# Webpay Configuration - Integration Environment
transbank.commerce.code=597055555532
transbank.api.key=579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C
transbank.environment=INTEGRATION

# Logging
logging.level.root=INFO
logging.level.com.webpaytest.api=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
